config/routes.rb
Rails.application.routes.draw do  
  devise_for :users
  resources :orders do
    resources :things
    resources :orders_users
    resources :settlements
  end
  root 'orders#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/order.rb
class Order < ApplicationRecord
  validates :name, length: { in: 3..20 }
  validates :owner, presence: true
  enum status: [ :open, :close, :finish ]
  has_many :things, dependent: :destroy
  has_many :settlements, dependent: :destroy
  has_and_belongs_to_many :orders_users, join_table: :orders_orders_users
  belongs_to :owner, :class_name => 'User'
  belongs_to :paymaster, :class_name => 'User', optional: true

  # @return [label, value]
  def self.translated_status_keys_for_select
    statuses.map do |status, _|
      [translated_status_key(status), status]
    end
  end

  def self.translated_status_key(key)
    I18n.t("activerecord.enums.#{model_name.i18n_key}.status.#{key}")
  end

  def create_thing(thing_params)
    thing = self.things.create(thing_params)
    if(!thing.errors.any?)
      if(self.cost.nil?)
        self.cost = thing.cost
      else
        self.cost += thing.cost
      end
    end
    self.save
    thing
  end

  def update(order_params)
    status = order_params[:status]
    paymaster = User.find(order_params[:paymaster_id])
    if self.status != status
      if(Order.statuses[:close] == Order.statuses[status] && self.open?)
        createSettlements 
        self.collected = 0
      elsif(Order.statuses[:open]  == Order.statuses[status])
        Settlement.where(["order_id = ?", self.id]).each {|settlement| settlement.destroy}
        self.collected = 0
      end
    end
    super(order_params.merge(paymaster: paymaster))
  end

  def delete_thing(thing_id)
    thing = self.things.find(thing_id)
    if(!thing.nil?)
      self.cost -= thing.cost
      self.save
    end
    thing.destroy
  end

  def delete_user(user_id)
    @user = self.orders_users.find(user_id)
    self.orders_users.delete(@user);
    self.save
  end

  def add_user(user)
    self.orders_users.push(user) unless self.include_user?(user)
    self.save
  end

  def include_user?(user)
    self.orders_users.exists?(user.id)
  end

  def is_owner?(user)
    !self.owner.nil? && self.owner.id == user.id
  end

  def is_paymaster?(user)
    !self.paymaster.nil? && self.paymaster.id == user.id
  end

  def can_delete?(user)
    self.is_owner?(user)
  end

  def can_edit?(user)
    self.is_owner?(user)
  end

  def can_settling?(user)
    self.is_owner?(user) || self.is_paymaster?(user)
  end

  def paymaster_candidate
    self.orders_users + [self.owner]
  end

  def recalc_collected
    self.collected = 0
    self.settlements.each { |settlement| self.collected += settlement.paid}
    self.save
  end

  private 

  def createSettlements
    grouper = Hash.new(0)
    self.things.each { |thing| grouper[thing.user] += thing.cost}
    grouper.each do |user, to_pay|
      self.settlements.push Settlement.create_for_order(self, user, to_pay)
    end
  end
end

app/models/orders_user.rb
class OrdersUser < User
    has_and_belongs_to_many :orders, join_table: :orders_orders_users
end

app/models/settlement.rb
class Settlement < ApplicationRecord
  belongs_to :order
  belongs_to :user

  def self.create_for_order(order, user, to_pay)
    settlement = Settlement.new
    settlement.order = order
    settlement.user = user
    settlement.to_pay = to_pay
    settlement.paid = 0
    settlement.save
    settlement
  end
end

app/models/thing.rb
class Thing < ApplicationRecord
  validates :name, length: { in: 1..20 }
  validates :cost, presence: true
  validates :user, presence: true
  validates :order, presence: true
  belongs_to :order
  belongs_to :user

  def is_owner?(user)
    self.user.id == user.id
  end

  def can_delete?(user)
    self.is_owner?(user) || self.order.is_owner?(user)
  end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
          :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  before_action :authenticate_user!
end

app/controllers/orders_base_controller.rb
class OrdersBaseController < ApplicationController
  protected

  def check_read_permission
    get_order
    unless @order.is_owner?(current_user) || @order.include_user?(current_user)
       redirect_to root_path
    end
  end

  def check_edit_permission
    get_order
    unless @order.can_edit?(current_user)
       redirect_to root_path
    end
  end

  def check_settling_permission
    get_order
    unless @order.can_settling?(current_user) && @order.close?
       redirect_to root_path
    end
  end

  private 
  def get_order
    id = params[:order_id]
    if(id.nil?)
        id = params[:id]
    end
    @order = Order.find(id)
  end
end

app/controllers/orders_controller.rb
class OrdersController < OrdersBaseController
  before_action :check_read_permission, only: [:show]
  before_action :check_edit_permission, only: [:edit, :update, :destroy]
  def index
    @orders = Order.left_outer_joins(:orders_users).where("orders.owner_id = ? OR orders_orders_users.orders_user_id = ?", current_user.id, current_user.id)
  end
  
  def new 
    @order = Order.new
  end
  
  def create
    @order = Order.new(order_params)
    @order.status = 'open'
    @order.owner = current_user
    @order.cost = 0.0
    if @order.save
      redirect_to @order
    else
      render 'new'
    end
  end
  
  def show
    @order = Order.find(params[:id])
  end
    
  def edit
    @order = Order.find(params[:id])
  end

  def update
    @order = Order.find(params[:id])
    if @order.update(order_params)
      redirect_to @order
    else
      render 'edit'
    end
  end

  def destroy
    @order = Order.find(params[:id])
    @order.destroy
    redirect_to orders_path
  end

  private
  
  def order_params
    params.require(:order).permit(:name, :status, :paymaster_id)
  end
end

app/controllers/orders_users_controller.rb
class OrdersUsersController < OrdersBaseController
  before_action :check_read_permission
  def create
    @order = Order.find(params[:order_id])
    @user = OrdersUser.find_by email: user_params[:email]
    if(!@user.nil?)
      @order.add_user(@user)
    else
      @order.errors[:base] << t(:user_is_not_exists)
    end
    render 'orders/edit'
  end

  def index
    redirect_to 'orders/edit'
  end

  def show
    redirect_to 'orders/edit'
  end

  def destroy
    @order = Order.find(params[:order_id])
    @order.delete_user(params[:id])
    render 'orders/edit'
  end

  private
  
  def user_params
    params.require(:orders_user).permit(:email)
  end
end

app/controllers/settlements_controller.rb
class SettlementsController < OrdersBaseController
  before_action :check_read_permission
  before_action :check_settling_permission, only: [:update]

  def update
    @order = Order.find(params[:order_id])
    @settlement = @order.settlements.find(params[:id])
    @settlement.update(settlement_params)
    @order.recalc_collected
    render 'orders/show'
  end

  def index
    render 'orders/show'
  end

  def show
    render 'orders/show'
  end

  private
  
  def settlement_params
    params.require(:settlement).permit(:paid)
  end
end

app/controllers/things_controller.rb
class ThingsController < OrdersBaseController
  before_action :check_read_permission
  before_action :check_delete_permission, only: [:destroy]
  before_action :check_change_permission, only: [:create, :destroy]
  def create
    @order = Order.find(params[:order_id])
    @thing = @order.create_thing(thing_params.merge(user: current_user))
    render 'orders/show'
  end

  def index
    render 'orders/show'
  end

  def show
    render 'orders/show'
  end

  def destroy
    @order = Order.find(params[:order_id])
    @order.delete_thing(params[:id])
    render 'orders/show'
  end

  private

  def thing_params
    params.require(:thing).permit(:name, :cost)
  end

  def check_delete_permission
    id = params[:id]
    thing = Thing.find(id)
    unless thing.can_delete?(current_user)
       redirect_to root_pathdelete
    end
  end

  def check_change_permission
    order = Order.find(params[:order_id])
    unless order.open?
       redirect_to root_pathdelete
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/orders_users_helper.rb
module OrdersUsersHelper
end

app/helpers/things_helper.rb
module ThingsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>JoinOrderPortal</title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/menu' %>
    <div class = "main_content">
      <%= yield %>
    </div>
  </body>
</html>

app/views/orders/edit.html.erb
<h2><%=t :order %></h2>
<%= form_for :order, url: order_path(@order), method: :patch , html: {class: "form-inline"} do |f| %>
  <%= render partial: 'shared/errors', locals: { validated: @order } %>
  	<%= f.label t :name , class: "form-control"%>:
	<%= f.text_field :name , class: "form-control"%>
	<%= f.label t :status , class: "form-control"%>:
    <%= f.select :status, options_for_select(Order.translated_status_keys_for_select, @order.status), {}, class: "form-control"%>
    <%= f.label t :paymaster , class: "form-control"%>:
    <%= f.select :paymaster_id, @order.paymaster_candidate.collect {|u| [ u.email, u.id ] }, {}, class: "form-control"%>
	<%= f.submit :value => t(:accept) , :class => "btn btn-primary" %>
<% end %>
<h3><%=t :users %></h3>
<table id="extraTable" data-language='{ "url":"/datatables/<%= t :datatablesLangName %>.json"}' class="table table-bordered">
  <thead>
    <tr class="thead-inverse">
      <th><%= t :name %></th>
      <th data-orderable="false"></th>
    </tr>
  </thead>
  <tbody>
    <% @order.orders_users.each do |user| %>
        <% if !user.errors.any? %>
            <tr>
                <td><%= user.email %></td>
                <td align="center" width="20"><%= link_to '', [@order, user], method: :delete, class: "glyphicon glyphicon-remove", data: { confirm: t(:are_you_sure) } %></td>
            </tr>
        <% end %>
    <% end %>
   </tbody>
</table>
<%= render "orders_users/form" %>

app/views/orders/index.html.erb
<table id="ordersTable" data-language='{ "url":"/datatables/<%= t :datatablesLangName %>.json"}' class="table table-bordered">
  <thead>
    <tr class="thead-inverse">
      <th><%= t :name %></th>
      <th><%= t :status %></th>
      <th><%= t :cost %></th>
      <th><%= t :collected %></th>
      <th><%= t :missing %></th>
      <th><%= t :owner %></th>
      <th><%= t :paymaster %></th>
      <th data-orderable="false"></th>
    </tr>
  </thead>
  <tbody>
    <% @orders.each do |order| %>
      <% missing = (order.cost.nil? ? 0 : order.cost) - (order.collected.nil? ? 0 : order.collected)%>
      <tr class="<%= missing > 0 ? "danger": missing == 0 ? "success" : "info" %>">
        <td><%= order.name %></td>
        <td><%= Order.translated_status_key(order.status) %></td>
        <td><%= number_with_precision(order.cost, precision:2) %></td>
        <td><%= number_with_precision(order.collected, precision:2) %></td>
        <td><%= number_with_precision(missing, precision: 2) %></td>
        <td>
          <% if(!order.owner.nil?)%>
            <%= order.owner.email %>
          <% end %>
        </td>
        <td>
          <% if(!order.paymaster.nil?)%>
            <%= order.paymaster.email %>
          <% end %>
        </td>
        <td align="center" width="60">
          <%= link_to '', order_path(order), class: "glyphicon glyphicon-info-sign"%>
          <% if order.can_edit?(current_user) %>
            <%= link_to '', edit_order_path(order), class: "glyphicon glyphicon-pencil" %>
          <% end %>
          <% if order.can_delete?(current_user) %>
            <%= link_to '', order_path(order), method: :delete, class: "glyphicon glyphicon-remove", data: { confirm: t(:are_you_sure) } %>
          <% end %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= link_to t(:new_order), new_order_path, class: "btn btn-primary"%>

app/views/orders/new.html.erb
<h1><%=t :new_order %></h1>
<%= render partial: 'shared/errors', locals: { validated: @order } %>
<%= form_for :order, url: orders_path, html: {class: "form-inline"} do |f| %>
  	<%= f.label t :name, class: "form-control"%>:
	<%= f.text_field :name, class: "form-control"%>
	<%= f.submit :value => t(:accept), :class => "btn btn-primary"%>
<% end %>

app/views/orders/show.html.erb
<h2><%=t :order %>:</h2>
<p>
	<strong><%=t :name %>:</strong>
	<%= @order.name %>
</p>
<p>
	<strong><%=t :status %>:</strong>
	<%= Order.translated_status_key(@order.status) %>
</p>
<p>
	<strong><%=t :total %> <%=t(:cost).downcase %>:</strong>
	<%= number_with_precision(@order.cost, precision:2)  %>
</p>
<p>
	<strong><%=t :collected %>:</strong>
	<%= number_with_precision(@order.collected, precision:2) %>
</p>
<p>
	<strong><%=t :missing %>:</strong>
	<%= number_with_precision((@order.cost.nil? ? 0 : @order.cost) - (@order.collected.nil? ? 0: @order.collected), precision: 2) %>
</p>
<p>
	<strong><%=t(:owner) %>:</strong>
	<%= @order.owner.email %>
</p>
<p>
	<strong><%=t(:paymaster) %>:</strong>
	<% if(!@order.paymaster.nil?)%>
		<%= @order.paymaster.email %>
	<% end %>
</p>
<% if @order.close? || @order.finish? %>
	<%= render "settlements/index" %>
<% end %>
<%= render "things/index" %>
<% if @order.open? %>
	<%= render "things/form" %>
<% end %>

app/views/orders_users/_form.html.erb
<h3><%=t :new_orders_users %></h3>
<%= form_for([@order, @order.orders_users.build], html: {class: "form-inline"}) do |f| %>
	<%= f.label t :email , class: "form-control"%>:
	<%= f.text_field :email , class: "form-control"%>
	<%= f.submit :value => t(:accept) , :class => "btn btn-primary" %>
<% end %>

app/views/settlements/_index.html.erb
<h3>Rozliczenie</h3>
<table id="settlementsTable" data-language='{ "url":"/datatables/<%= t :datatablesLangName %>.json"}' class="table table-bordered">
	<thead>
		<tr class="thead-inverse">
			<th><%=t :purchaser %></th>
			<th><%=t :to_pay %></th>
			<th><%=t :paid %></th>
            <th><%=t :missing%>
		</tr>
	</thead>
	<tbody>
		<% @order.settlements.each do |settlement| %>
            <% missing =settlement.to_pay - settlement.paid %>
            <tr class="<%= missing > 0 ? "danger": missing == 0 ? "success" : "info" %>">
                <td><%= settlement.user.email %></td>
                <td><%= number_with_precision(settlement.to_pay, precision:2) %></td>
                <td>
                    <% if @order.can_settling?(current_user) && @order.close? %>
                        <%= form_for [@order, settlement], url: order_settlement_path(@order, settlement), method: :patch , html: {class: "form-inline"} do |f| %>
                            <%= f.number_field(:paid, min: 0, step: 0.01, class: "form-control") %> 
                            <%= f.submit :value => t(:save), :class => "btn btn-primary" %>
                        <% end %>
                    <% elsif %>
                        <%= number_with_precision(settlement.paid, precision:2) %>
                    <% end %>
                </td>
                <td><%= number_with_precision(missing, precision: 2) %></td>
            </tr>
		<% end %>
	</tbody>
</table>

app/views/shared/_errors.html.erb
<% if validated.errors.any? %>
    <% validated.errors.full_messages.each do |msg| %>
            <div class="alert alert-danger alert-dismissable">
            <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
            <%= msg %>
        </div>
    <% end %>
<% end %>

app/views/shared/_menu.html.erb
<div id="navbar">
    <nav class="navbar navbar-inverse navbar-fixed-top">
        <div class="container-fluid">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a id="navbar-brand" class="navbar-brand" href="#">JointOrderPortal  </a>
            </div>
            <div class="collapse navbar-collapse" id="myNavbar">
                <ul id="menuOptions" class="nav navbar-nav">
                    <li><a href="/">Strona głowna</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    <% if(user_signed_in?) %>
                        <li><a href=""><%= current_user.email %></a></li>
                        <li><%= link_to t(:signOut), destroy_user_session_path, :method => :delete %></li>
                    <% else %>
                        <%= render "devise/shared/links"%>
                    <% end %>
                </ul>
            </div>
        </div>
    </nav>
</div>

app/views/things/_form.html.erb
<h3><%=t :new_order_thing %></h3>
<% @order.things.each do |thing| %>
	<%= render partial: 'shared/errors', locals: { validated: thing } %>
<% end %>
<%= form_for([@order, @order.things.build], html: {class: "form-inline"}) do |f| %>
	<%= f.label t :name , class: "form-control"%>:
	<%= f.text_field :name , class: "form-control"%>
	<%= f.label t :cost , class: "form-control"%>:
	<%= f.number_field(:cost, min: 0, step: 0.01, class: "form-control")  %>
	<%= f.submit :value => t(:accept) , :class => "btn btn-primary" %>
<% end %>

app/views/things/_index.html.erb
<h3><%=t :things %></h3>
<table id="thingsTable" data-language='{ "url":"/datatables/<%= t :datatablesLangName %>.json"}' class="table table-bordered">
	<thead>
		<tr class="thead-inverse">
			<th><%=t :name %></th>
			<th><%=t :cost %></th>
			<th><%=t :purchaser %></th>
            <% if @order.open? %>
			    <th data-orderable="false"></th>
            <% end %>
		</tr>
	</thead>
	<tbody>
		<% @order.things.each do |thing| %>
			<% if !thing.errors.any? %>
				<tr>
					<td><%= thing.name %></td>
                    <td><%= number_with_precision(thing.cost, precision:2) %></td>
					<td><%= thing.user.email %></td>
                    <% if @order.open? %>
                        <td align="center" width="20">
                        <% if thing.can_delete?(current_user) %>
                            <%= link_to '', [thing.order, thing], method: :delete, class: "glyphicon glyphicon-remove", data: { confirm: t(:are_you_sure) } %>
                        <% end %>
                        </td>
                    <% end %>
				</tr>
			<% end %>
		<% end %>
	</tbody>
</table>